# Generated by Django 4.1.4 on 2023-02-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Iciciapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="employee_details", table=None,),
    ]
