# Generated by Django 4.1.4 on 2023-02-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Iciciapp", "0002_alter_employee_details_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="employee_details", table="employee",),
    ]
